### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by nishkalavallabhi** [MantisAI/nervaluate#58]
What is a good way to cite nervaluate if we use it in our work? I did not find a citation in the usual locations such as a README.

**Comment by ivyleavedtoadflax** [comment]
Thanks @nishkalavallabhi we'll add a CITATIONS file. Bear with us...

**Comment by ivyleavedtoadflax** [comment]
I see it's already been cited in a few places!

## Papers

Heddes J, Meerdink P, Pieters M, Marx M. The Automatic Detection of Dataset Names in Scientific Articles. Data. 2021; 6(8):84. https://doi.org/10.3390/data6080084

Wróblewska, A., Kaliska, A., Pawłowski, M., Wiśniewski, D., Sosnowski, W., & Ławrynowicz, A. (2022). TASTEset -- Recipe Dataset and Food Entities Recognition Benchmark. arXiv [cs.CL]. Ανακτήθηκε από http://arxiv.org/abs/2204.07775

Article Source: [A pre-training and self-training approach for biomedical named entity recognition](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0246310)
Gao S, Kotevska O, Sorokine A, Christian JB (2021) A pre-training and self-training approach for biomedical named entity recognition. PLOS ONE 16(2): e0246310. https://doi.org/10.1371/journal.pone.0246310

Chester Palen-Michel, Nolan Holley, and Constantine Lignos. 2021. [SeqScore: Addressing Barriers to Reproducible Named Entity Recognition Evaluation](https://aclanthology.org/2021.eval4nlp-1.5). In Proceedings of the 2nd Workshop on Evaluation and Comparison of NLP Systems, pages 40–50, Punta Cana, Dominican Republic. Association for Computational Linguistics.

Siim Orasmaa, Kadri Muischnek, Kristjan Poska, and Anna Edela. 2022. [Named Entity Recognition in Estonian 19th Century Parish Court Records](https://aclanthology.org/2022.lrec-1.568). In Proceedings of the Thirteenth Language Resources and Evaluation Conference, pages 5304–5313, Marseille, France. European Language Resources Association.

Gao S, Kotevska O, Sorokine A, Christian JB. A pre-training and self-training approach for biomedical named entity recognition. PLoS One. 2021 Feb 9;16(2):e0246310. doi: 10.1371/journal.pone.0246310. PMID: 33561139; PMCID: PMC7872256.

## Conference Proceedings

Ruosch, Florian; Sarasua, Cristina; Bernstein, Abraham (2022). BAM: Benchmarking Argument Mining
on Scientific Documents. In: The AAAI-22 Workshop on Scientific Document Understanding at the
Thirty-Sixth AAAI Conference on Artificial Intelligence (AAAI-22), online due to COVID-19, 1 March
2022, CEUR Workshop Proceedings.
https://www.zora.uzh.ch/id/eprint/217835/1/2022_SDU_AAAI_RuoschEtAl__CEUR_.pdf

## Theses

Schouten, H.J. (2021) Geoparsing Dutch Archival Descriptions. A Pipeline for Extracting and Linking Toponyms to the Linked Open Data Cloud. _Msc Thesis_, Utrecht University. Available at: https://studenttheses.uu.nl/handle/20.500.12932/41190?show=full

## elsewhere

https://medium.com/neuralspace/named-entity-recognition-at-your-fingertips-a-comparative-study-of-various-autonlp-engines-part-f5307a4a7bdc

**Comment by nishkalavallabhi** [comment]
Yes, I am aware of that. I just wanted to check if there is any official citation, as some repos keep that too. Thanks.

**Comment by ivyleavedtoadflax** [comment]
No worries - actually I was just posting this for @davidsbatista and myself - I was unaware that it had been cited anywhere!

**Comment by nishkalavallabhi** [comment]
Oh, I found out about it only while reading some paper a few months ago. It is cited in quite a few papers. E.g., this LREC 2022 paper too: http://lrec-conf.org/proceedings/lrec2022/pdf/2022.lrec-1.475.pdf

**Comment by ivyleavedtoadflax** [comment]
> Oh, I found out about it only while reading some paper a few months ago. It is cited in quite a few papers. E.g., this LREC 2022 paper too: http://lrec-conf.org/proceedings/lrec2022/pdf/2022.lrec-1.475.pdf

Wow great - thanks - i'll add it to the list!

**Comment by davidsbatista** [comment]
@ivyleavedtoadflax what do you say? Time for us to wrap up some of the ideas behind this software package, and make a short paper out of it? 

maybe just pointing out, experimentally, when it's advantegous or not to mesaure NER task using this approach - not to with the main intent to produce break through scientific adavance - but just to cristalize this small idea of evaluating NER at the token level but full entity name - and providing an out-of-the-box solution to it

happy to hear what you think :)

**Comment by ivyleavedtoadflax** [comment]
Yess @davidsbatista I'm definitely in for that.
